{% set name = "maup" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb30fbd504729c0bfb57224a870e9fe3ff2cb51211783f8824d1e14e523c4747

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - pandas
    - shapely
    - geopandas
    - tqdm
    - python >=3.6

test:
  imports:
    - maup

about:
  home: https://github.com/mggg/maup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The geospatial toolkit for redistricting data

  description: |
    maup is the geospatial toolkit for redistricting data. The package streamlines
    the basic workflows that arise when working with census blocks and precinct
    shapefiles.
  doc_url: https://github.com/mggg/maup
  dev_url: https://github.com/mggg/maup

extra:
  recipe-maintainers:
    - maxhully
